<a href="https://colab.research.google.com/github/krakowiakpawel9/data-science-bootcamp/blob/master/01_wprowadzenie/03_funkcje_statystyczne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  


Podstawowa biblioteka do obliczeń numerycznych w języku Python.

Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```



### Funkcje statystyczne

In [0]:
import numpy as np
np.__version__

'1.17.4'

In [0]:
price = np.array([[12.40, 12.80, 11.90, 12.60, 1000],
                  [12.50, 13.00, 11.70, 12.20, 2000],
                  [12.20, 13.40, 12.20, 13.20, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


sum()

In [0]:
price.sum(axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [0]:
np.sum(price, axis=0)

array([  37.1,   39.2,   35.8,   38. , 4500. ])

min()

In [0]:
price.min(axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [0]:
np.min(price, axis=0)

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

max()

In [0]:
price.max(axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

In [0]:
np.max(price, axis=0)

array([  12.5,   13.4,   12.2,   13.2, 2000. ])

median()

In [0]:
np.median(price, axis=0)

array([  12.4,   13. ,   11.9,   12.6, 1500. ])

mean()

In [0]:
price.mean(axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

In [0]:
np.mean(price, axis=0)

array([  12.36666667,   13.06666667,   11.93333333,   12.66666667,
       1500.        ])

std()

In [0]:
price.std(axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

In [0]:
np.std(price, axis=0)

array([1.24721913e-01, 2.49443826e-01, 2.05480467e-01, 4.10960934e-01,
       4.08248290e+02])

var()

In [0]:
price.var(axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])

In [0]:
np.var(price, axis=0)

array([1.55555556e-02, 6.22222222e-02, 4.22222222e-02, 1.68888889e-01,
       1.66666667e+05])